baseurl: "https://www.stormca.st/"
contentdir: "content"
languageCode: "en-us"
layoutdir: "layouts"
metaDataFormat: "yaml"
publishdir: "build"
title: "Stormcast"

params:
  description: "The most awesome web security podcast. Coding, security, and lots of laughs."
  subtitle: "The Most Awesome Web Security Podcast"
  mailchimpFormAction: "//stormpath.us3.list-manage.com/subscribe/post?u=a277933d5f9c347b1bcc00936&amp;id=ee5a4d5d4a"
  navLinks:
    - title: "Twitter"
      url: "https://twitter.com/thestormcast"
      class: "fa-twitter"
    - title: "Google+"
      url: "https://plus.google.com/u/0/b/107195188379868867389/107195188379868867389"
      class: "fa-google-plus"
    - title: "Facebook"
      url: "https://www.facebook.com/thestormcast"
      class: "fa-facebook"
    - title: "ITunes"
      url: "https://itunes.apple.com/us/podcast/stormcast/id1073236043"
      class: "fa-apple"
