baseurl = "https://stormca.st/"
contentdir = "content"
disableRSS = true
languageCode = "en-us"
layoutdir = "layouts"
metaDataFormat = "yaml"
publishdir = "public"
title = "Stormcast"

[params]
  description = "The most awesome web security podcast. Coding, security, and lots of laughs."
  subtitle = "The Most Awesome Web Security Podcast"
